[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.04/platform-espressif32.zip
board = esp32dev
framework = arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

board_build.partitions = min_spiffs.csv
board_build.filesystem = spiffs

lib_deps =
    adafruit/RTClib
    adafruit/Adafruit VEML7700 Library
    adafruit/Adafruit BusIO
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit NeoPixel
    bblanchon/ArduinoJson @ ^6
    knolleary/PubSubClient
 